<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>SNP_Evolution</AssemblyName>
    <RootNamespace>SnpEvolution</RootNamespace>
    <Version>1.0.0</Version>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>snp-evolution</ToolCommandName>
    <PackageId>SNP_Evolution</PackageId>
    <PackageOutputPath>$(MSBuildThisFileDirectory)../nupkg</PackageOutputPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Simulation/Metal/Simulation.metal" LogicalName="SnpEvolution.Simulation.Metal.Simulation.metal" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SNP_Evolution.Tests" />
  </ItemGroup>

</Project>
