using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using SnpEvolution.Compilation;
using SnpEvolution.Evolution.Fitness;
using SnpEvolution.Evolution.Genome;
using SnpEvolution.Evolution.Search;
using SnpEvolution.Evolution.Tasks;
using SnpEvolution.Networks;
using SnpEvolution.Simulation;
using SnpEvolution.Storage;

namespace SnpEvolution.Cli
{
    // Compile, then shrink: finds a program for the target at a higher level, compiles it into a network that is
    // correct by construction, checks that it is, and evolves it smaller while it stays correct. A sequence of gaps
    // is fitted with a recurrence; a set is generated by a register program, evolved or read from a file.
    internal static class CompileSession
    {
        public sealed record Options(int ShrinkGenerations, int ProgramGenerations, string? ProgramFile, bool ProgramLexicase = true);

        public static int Run(Settings settings, Options options, Random random, Action<string> log)
        {
            OutputTarget target = settings.Target;
            ITask task = target.CreateTask(settings.FitnessFunction.Create(settings));
            string folder = EvolutionSession.NewOutputFolder();
            Directory.CreateDirectory(folder);
            Network compiled;
            ISimulationEngine engine;
            int steps = settings.MaxSteps;
            int repetitions = settings.Repetitions;
            Recurrence? fitted = null;
            switch (target.Kind)
            {
                case TargetKind.Sequence:
                    if (Recurrence.Fit(target.Values) is not Recurrence recurrence)
                    {
                        log($"No recurrence of order up to {Recurrence.MaxOrder} with coefficients up to {Recurrence.MaxCoefficient} gives {target}, so it cannot be compiled.");
                        return 1;
                    }
                    log($"Recurrence: {recurrence}.");
                    NetworkFiles.SaveText(recurrence + Environment.NewLine, Path.Combine(folder, "Program.txt"));
                    compiled = RecurrenceCompiler.Compile(recurrence);
                    engine = settings.Engine.Create(settings);
                    // A spike train is only matched by a network that gives it on every run, so a few runs show that.
                    repetitions = Math.Min(repetitions, RunAdvisor.MaxUsefulRepetitions);
                    fitted = recurrence;
                    break;
                case TargetKind.Set:
                    if (FindProgram(target, settings, options, random, log) is not RegisterProgram program)
                    {
                        return 1;
                    }
                    log($"Register program:{Environment.NewLine}{program}");
                    NetworkFiles.SaveText(program.ToString(), Path.Combine(folder, "Program.txt"));
                    compiled = RegisterMachineCompiler.Compile(program);
                    // Every choice is followed, so rare outputs are seen.
                    // Runs last as long as the slowest computation up to the search's last bound: no module takes more
                    // than four steps an instruction, and the output counts down.
                    long bound = ProgramSearch.StageBounds(target.Values.Distinct().OrderBy(number => number).ToList())[^1];
                    int instructionSteps = program.Generate(outputLimit: bound, valueLimit: 4 * bound + 4).Steps;
                    engine = new ExhaustiveCpuEngine();
                    steps = (int)Math.Max(steps, 4L * (instructionSteps + 2) + bound + 10);
                    break;
                default:
                    log("Only sequence and set targets can be compiled.");
                    return 1;
            }
            log($"Compiled: {ShrinkRun.Describe(compiled)}.");
            Save(compiled, folder, "Compiled");
            SimulationOptions simulation = settings.SimulationOptions with { MaxSteps = steps, Repetitions = repetitions, Timing = OutputTiming.Interval };
            var evaluator = new FitnessEvaluator(engine, task, simulation, settings.SolvedRetestCount, random);
            FitnessResult check = evaluator.Evaluate(compiled);
            log($"The compiled network scores {check.Fitness:0.000}: {check.Description}");
            var shrink = new ShrinkRun(compiled, evaluator, ShrinkFactory(settings, compiled, random), settings.PopulationSize, random, log);
            if (options.ShrinkGenerations == 0 || !shrink.Run(options.ShrinkGenerations))
            {
                log($"Saved to {folder}");
                return Solved.Solves(check.Fitness) ? 0 : 2;
            }
            NetworkFiles.SaveText(FitnessCsv.Format(shrink.FitnessHistory), Path.Combine(folder, "Shrunk.csv"));
            Save(shrink.Smallest, folder, "Shrunk");
            log($"{Environment.NewLine}Smallest correct network after {shrink.Generations} generations of shrinking: {ShrinkRun.Describe(shrink.Smallest)}, " +
                $"from {ShrinkRun.Describe(compiled)}.{Environment.NewLine}{NetworkNotation.Format(shrink.Smallest)}");
            if (fitted != null)
            {
                // Shrinking only checks the values given, so it may drop what the gaps after them need.
                var further = new SequenceTask("continued", fitted.Values(target.Values.Count + ContinuedValues).Select(value => (int)Math.Min(int.MaxValue, value)).ToList());
                var continued = new FitnessEvaluator(engine, further, simulation, settings.SolvedRetestCount, random);
                log($"Past the target, the next {ContinuedValues} values of the recurrence: compiled {Continues(continued, compiled)}, shrunk {Continues(continued, shrink.Smallest)}.");
            }
            log($"Saved to {folder}");
            return 0;
        }

        private const int ContinuedValues = 4;

        private static string Continues(FitnessEvaluator evaluator, Network network) =>
            evaluator.IsReliablySolved(network) ? "carries on" : $"does not ({evaluator.Evaluate(network).Description})";

        private static RegisterProgram? FindProgram(OutputTarget target, Settings settings, Options options, Random random, Action<string> log)
        {
            if (options.ProgramFile != null)
            {
                try
                {
                    var given = RegisterProgram.Parse(File.ReadAllText(options.ProgramFile));
                    if (given.Problem() is string problem)
                    {
                        log($"{options.ProgramFile} cannot be compiled: {problem}.");
                        return null;
                    }
                    return given;
                }
                catch (Exception exception) when (exception is IOException or FormatException or UnauthorizedAccessException)
                {
                    log($"Could not read a program from {options.ProgramFile}: {exception.Message}");
                    return null;
                }
            }
            log($"Evolving a register program for {target}.");
            var search = new ProgramSearch(target.Values, new ProgramSearchSettings(options.ProgramGenerations, Math.Max(settings.PopulationSize, 100), Lexicase: options.ProgramLexicase), random);
            ScoredProgram best = search.Run(log);
            log(Solved.Solves(best.Fitness)
                ? $"Found a program in {search.GenerationsRun} generations."
                : $"No program generates exactly {target} after {search.GenerationsRun} generations; compiling the best, with fitness {best.Fitness:0.000} " +
                    $"on numbers up to {search.Bounds[search.Stage]} (stage {search.Stage + 1}/{search.Bounds.Count}).");
            return best.Program;
        }

        // The usual genome space, widened to hold the compiled network so no edit is cut short by a limit it already breaks.
        private static NetworkFactory ShrinkFactory(Settings settings, Network compiled, Random random)
        {
            List<Rule> rules = compiled.Neurons.SelectMany(neuron => neuron.Rules).ToList();
            GenomeSpace space = settings.GenomeSpace(0) with
            {
                RuleForm = RuleForm.Standard,
                MaxNeurons = compiled.Neurons.Count,
                MaxRulesPerNeuron = Math.Max(3, compiled.Neurons.Max(neuron => neuron.Rules.Count)),
                MaxDelay = Math.Max(settings.MaxDelay, rules.Max(rule => rule.Delay)),
                MaxProduce = Math.Max(settings.MaxProduce, rules.Max(rule => rule.Produce)),
                MaxInitialSpikes = (int)Math.Min(int.MaxValue, Math.Max(settings.MaxInitialSpikes, compiled.Neurons.Max(neuron => neuron.InitialSpikes))),
            };
            return new NetworkFactory(space, new ExpressionGenerator(settings.MutationTemplates, Settings.MaxSpikeGroupSize, random), random);
        }

        private static void Save(Network network, string folder, string stem)
        {
            NetworkFiles.Save(network, Path.Combine(folder, stem + ".json"));
            NetworkFiles.SaveText(NetworkNotation.Format(network), Path.Combine(folder, stem + ".txt"));
            NetworkFiles.SaveText(NetworkGraph.Svg(network), Path.Combine(folder, stem + ".svg"));
            NetworkFiles.SaveText(NetworkPage.Html(network, stem), Path.Combine(folder, stem + ".html"));
        }
    }
}
