using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using SnpEvolution.Compilation;
using SnpEvolution.Model;
using SnpEvolution.Search;
using SnpEvolution.Search.Fitness;
using SnpEvolution.Search.Genome;
using SnpEvolution.Simulation;
using SnpEvolution.Specs.Accounting;
using SnpEvolution.Specs.Tasks;
using SnpEvolution.Storage;

namespace SnpEvolution.Application
{
    // Compile, then shrink: finds a program for the target at a higher level, compiles it into a network that is
    // correct by construction, checks that it is, and evolves it smaller while it stays correct. A sequence of gaps
    // is fitted with a recurrence; a set is generated by a register program, evolved or read from a file.
    // ShrinkGenerations 0 only compiles; ProgramGenerations and ProgramLexicase are for evolving a register program.
    public sealed record CompileRequest(int ShrinkGenerations = CompileService.DefaultShrinkGenerations, string? ProgramFile = null,
        int ProgramGenerations = CompileService.DefaultProgramGenerations, bool ProgramLexicase = true);

    // Compiled is null when the target could not be compiled, with the reason in the log; Solved says whether the
    // network kept, shrunk or not, solves the target.
    public sealed record CompileResult(Network? Compiled, bool Solved);

    public static class CompileService
    {
        public const int DefaultShrinkGenerations = 300;
        public const int DefaultProgramGenerations = 2000;

        private static readonly CompileResult NotCompiled = new CompileResult(null, false);

        public static CompileResult Run(Settings settings, CompileRequest request, Random random, Action<string> log)
        {
            var budget = new EvaluationBudget();
            OutputTarget target = settings.Target;
            ITask task = target.CreateTask(settings.FitnessFunction.Create(settings));
            string folder = RunFolders.CreateOutputFolder();
            Network compiled;
            ISimulationEngine engine;
            int steps = settings.MaxSteps;
            int repetitions = settings.Repetitions;
            Recurrence? fitted = null;
            switch (target.Kind)
            {
                case TargetKind.Sequence:
                    if (Recurrence.Fit(target.Values) is not Recurrence recurrence)
                    {
                        log($"No recurrence of order up to {Recurrence.MaxOrder} with coefficients up to {Recurrence.MaxCoefficient} gives {target}, so it cannot be compiled.");
                        return NotCompiled;
                    }
                    log($"Recurrence: {recurrence}.");
                    NetworkFiles.SaveText(recurrence + Environment.NewLine, Path.Combine(folder, "Program.txt"));
                    compiled = RecurrenceCompiler.Compile(recurrence);
                    engine = settings.Engine.Create(settings);
                    // A spike train is only matched by a network that gives it on every run, so a few runs show that.
                    repetitions = Math.Min(repetitions, RunAdvisor.MaxUsefulRepetitions);
                    fitted = recurrence;
                    break;
                case TargetKind.Set:
                    if (FindProgram(target, task, settings, request, budget, random, log) is not RegisterProgram program)
                    {
                        return NotCompiled;
                    }
                    log($"Register program:{Environment.NewLine}{program}");
                    NetworkFiles.SaveText(program.ToString(), Path.Combine(folder, "Program.txt"));
                    compiled = RegisterMachineCompiler.Compile(program);
                    // Every choice is followed, so rare outputs are seen.
                    // Runs last as long as the slowest computation up to the search's last bound: no module takes more
                    // than four steps an instruction, and the output counts down.
                    long bound = ProgramScoring.StageBounds(target.Values.Distinct().OrderBy(number => number).ToList())[^1];
                    int instructionSteps = program.Generate(outputLimit: bound, valueLimit: 4 * bound + 4).Steps;
                    engine = new ExhaustiveCpuEngine();
                    steps = (int)Math.Max(steps, 4L * (instructionSteps + 2) + bound + 10);
                    break;
                default:
                    log("Only sequence and set targets can be compiled.");
                    return NotCompiled;
            }
            log($"Compiled: {ShrinkSearch.Describe(compiled)}.");
            RunOutput.SaveNetwork(compiled, folder, "Compiled");
            SimulationOptions simulation = settings.SimulationOptions with { MaxSteps = steps, Repetitions = repetitions, Timing = OutputTiming.Interval };
            var scoring = new NetworkScoring(() => engine, simulation, settings.SolvedRetestCount);
            FitnessEvaluator evaluator = scoring.Evaluator(task, budget, random);
            FitnessResult check = evaluator.Evaluate(compiled);
            log($"The compiled network scores {check.Fitness:0.000}: {check.Description}");
            if (request.ShrinkGenerations == 0 || !StartsShrink(evaluator, compiled, check, log))
            {
                log($"Saved to {folder}");
                return new CompileResult(compiled, Solved.Solves(check.Fitness));
            }
            var start = new Individual(compiled);
            start.Record(check);
            var setup = new NetworkSetup(settings.PopulationSize, settings.MutationRate, ShrinkFactory(settings, compiled, random), () => compiled, scoring);
            SearchOutcome<Individual> shrink = SearchCatalog.Shrink.Run(new SearchRequest<Individual>(task, budget, random, log)
            {
                Seeds = new[] { start },
                MaxGenerations = request.ShrinkGenerations,
                Networks = setup,
            });
            Network smallest = shrink.Best?.Genes ?? compiled;
            NetworkFiles.SaveText(FitnessCsv.Format(shrink.History), Path.Combine(folder, "Shrunk.csv"));
            RunOutput.SaveNetwork(smallest, folder, "Shrunk");
            log($"{Environment.NewLine}Smallest correct network after {shrink.Generations} generations of shrinking: {ShrinkSearch.Describe(smallest)}, " +
                $"from {ShrinkSearch.Describe(compiled)}.{Environment.NewLine}{NetworkNotation.Format(smallest)}");
            if (fitted != null)
            {
                // Shrinking only checks the values given, so it may drop what the gaps after them need.
                var further = new SequenceTask("continued", fitted.Values(target.Values.Count + ContinuedValues).Select(value => (int)Math.Min(int.MaxValue, value)).ToList());
                FitnessEvaluator continued = scoring.Evaluator(further, budget, random);
                log($"Past the target, the next {ContinuedValues} values of the recurrence: compiled {Continues(continued, compiled)}, shrunk {Continues(continued, smallest)}.");
            }
            log($"Saved to {folder}");
            return new CompileResult(compiled, true);
        }

        private const int ContinuedValues = 4;

        private static string Continues(FitnessEvaluator evaluator, Network network) =>
            evaluator.ConfirmSolved(network).Solved ? "carries on" : $"does not ({evaluator.Evaluate(network).Description})";

        // A shrink keeps only networks as good as the one it starts from, so that one must reliably solve the task.
        private static bool StartsShrink(FitnessEvaluator evaluator, Network compiled, FitnessResult check, Action<string> log)
        {
            if (!evaluator.ConfirmSolved(compiled).Solved)
            {
                log($"The starting network does not reliably solve {evaluator.Task.Name} (fitness {check.Fitness:0.000}), so there is nothing to shrink.");
                return false;
            }
            log($"Shrinking from {ShrinkSearch.Describe(compiled)}.");
            return true;
        }

        private static RegisterProgram? FindProgram(OutputTarget target, ITask task, Settings settings, CompileRequest request, EvaluationBudget budget, Random random, Action<string> log)
        {
            if (request.ProgramFile != null)
            {
                try
                {
                    var given = RegisterProgram.Parse(File.ReadAllText(request.ProgramFile));
                    if (given.Problem() is string problem)
                    {
                        log($"{request.ProgramFile} cannot be compiled: {problem}.");
                        return null;
                    }
                    return given;
                }
                catch (Exception exception) when (exception is IOException or FormatException or UnauthorizedAccessException)
                {
                    log($"Could not read a program from {request.ProgramFile}: {exception.Message}");
                    return null;
                }
            }
            log($"Evolving a register program for {target}.");
            var search = new ProgramSearch(new ProgramSearchSettings(Math.Max(settings.PopulationSize, 100), Lexicase: request.ProgramLexicase));
            SearchOutcome<RegisterProgram> best = search.Run(new SearchRequest<RegisterProgram>(task, budget, random, log) { MaxGenerations = request.ProgramGenerations });
            log(best.Solved
                ? $"Found a program in {best.Generations} generations."
                : $"No program generates exactly {target} after {best.Generations} generations; compiling the best, with fitness {best.Fitness:0.000}, {best.Description}.");
            return best.Best;
        }

        // The usual genome space, widened to hold the compiled network so no edit is cut short by a limit it already breaks.
        private static NetworkFactory ShrinkFactory(Settings settings, Network compiled, Random random)
        {
            List<Rule> rules = compiled.Neurons.SelectMany(neuron => neuron.Rules).ToList();
            GenomeSpace space = settings.GenomeSpace(0) with
            {
                RuleForm = RuleForm.Standard,
                MaxNeurons = compiled.Neurons.Count,
                MaxRulesPerNeuron = Math.Max(3, compiled.Neurons.Max(neuron => neuron.Rules.Count)),
                MaxDelay = Math.Max(settings.MaxDelay, rules.Max(rule => rule.Delay)),
                MaxProduce = Math.Max(settings.MaxProduce, rules.Max(rule => rule.Produce)),
                MaxInitialSpikes = (int)Math.Min(int.MaxValue, Math.Max(settings.MaxInitialSpikes, compiled.Neurons.Max(neuron => neuron.InitialSpikes))),
            };
            return new NetworkFactory(space, new ExpressionGenerator(settings.MutationTemplates, Settings.MaxSpikeGroupSize, random), random);
        }
    }
}
