<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <Version>1.0.0</Version>
    <IsPackable>true</IsPackable>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>snp-evolution</ToolCommandName>
    <PackageId>SNP_Evolution</PackageId>
    <PackageOutputPath>$(MSBuildThisFileDirectory)../nupkg</PackageOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\Application.csproj" />
  </ItemGroup>

</Project>
